### PR TITLE
Close when menu is opening

### PR DESCRIPTION
**Pull request by Claeysson**
If a user taps an item before the menu is fully open the action is triggered but the menu doesn't close. This fixes the issue

### CODE REVIEW

**Comment by jjochen** [comment]
Awesome, I will update the tests.

**Comment by Claeysson** [comment]
My solution isn’t perfect. The app will crash if the menu button is double tapped. Maybe you can look in to it. 

Thanks!

**Comment by jjochen** [comment]
> My solution isn’t perfect. The app will crash if the menu button is double tapped. Maybe you can look in to it.
> 
> Thanks!

Will do

**Comment by jjochen** [comment]
@Claeysson I pushed to the wrong (my) remote and closed the PR by mistake. Could you reopen it, please?

**Comment by jjochen** [comment]
I recreated this PR [here](#233)

**Comment by jjochen** [comment]
I recreated this PR [here].(https://github.com/jjochen/JJFloatingActionButton/pull/233)

**Pull request merged**
